name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker buildx build . --tag kickrme/soundcore:$GITHUB_SHA --platform linux/arm64
    - name: Push the Image
      run: docker push kickrme/soundcore:$GITHUB_SHA
